### ISSUE TITLE
Remove All Dead Code & Cleanup Setup

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/LLMonFHIR#56]
### Problem

In response to #53 we should aim to remove all dead code that might not be fully required for the app to aim to more easily support it for our usability validation study.

### Solution

We should integrate [periphery](https://github.com/peripheryapp/periphery) into this repo.

We can easily add the following job in the static analysis section of the GitHub Actions in this repo:
```yml
  periphery:
    name: Periphery
    uses: StanfordBDHG/.github/.github/workflows/periphery.yml@v2
    permissions:
      contents: read
    with:
      runsonlabels: '["macOS", "self-hosted"]'
```

We might also need to add a small configuration file as done in our other project, e.g., [ENGAGE-HF](https://github.com/StanfordBDHG/ENGAGE-HF-iOS/blob/main/.periphery.yml).

As part of this we should resolve all periphery warnings in the same PR enabling them. Installing periphery locally will help a lot to resolve this.

### Additional context

Should be addressed when #53 is merged.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines
